### ISSUE TITLE
Test Cases for Authentication

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#1]

**Comment by PolarcX** [comment]
TC01 - Login Page - Authenticate Successfully
Test description : A registered user should be able to successfully login into the website

Preconditions: The user must already have a registered email and password

Test Steps : 1. Navigate to the website
                   2. Enter the Email of registered user in 'email' field
                   3. Enter the Password of registered user in 'password' field
                   4. Click 'Sign In'

Expected result: Website should successfully authenticate the user, redirecting the user to the next page

Test Values: Email='123@abc.com' Password='123123'

//-------------------------------------------------------------------------------------------//

TC02 - Login Page - Authentication failed
Test description : Users that have not registered should not be able to login into the website

Preconditions: The user does not have a registered email and password

Test Steps : 
1. Navigate to the website
2. Enter the Email of unregistered user in 'email' field
3. Enter the Password of unregistered user in 'password' field
4. Click 'Sign In'

Expected result: Website should fail to authenticate the user, 'email or password is incorrect' error should be shown, and the user stays on the login page.

Test Values: Email='122@abb.com' Password='111111'

**Comment by PolarcX** [comment]
@bokiex Removed TC01-2 - Login Page - Invalid email syntax
Changed 
TC01 - Login Page - Authenticate Successfully
TC01-1 - Login Page - Authentication failed

Pending review

**Comment by bokiex** [comment]
Reviewed.
