### ISSUE TITLE
Test Case for sign up functionality

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#17]
Test case needed for sign up functionality for https://github.com/bokiex/eti_todo/issues/5 feature.

**Comment by PolarcX** [comment]
TC 05 - Sign up
Test Description: User signs up for the website
Preconditions: -nil-
Test Steps:
1.Click on Sign up
2.Enter Email in the "email" field
3.Enter Username in the "username" field
4.Enter Password in the "password" field
5.Click Sign up

Expected results: Account is created and stored in the database
Test Values: email="123@gmail.com" username="whysee" password=123123abc"

TC 05-1 - Sign up error
Test Description: User signs up for the website
Preconditions: -nil-
Test Steps:
1.Click on Sign up
2.Enter Email in the "email" field
3.Enter Username in the "username" field
4.Enter Password in the "password" field
5.Click Sign up

Expected results:
Incorrect email syntax error should show 
Username should be 6 to 12 characters long
Password should be 6 to 12 characters long & include numbers and Caps
Test Values: email="123@gail.com" username="why" password=123"

**Comment by PolarcX** [comment]
@bokiex Done and Pending review

**Comment by bokiex** [comment]
Reviewed and closed
