### ISSUE TITLE
Test case for filter functionality for to-do function

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#18]
Additional filter function to be added to https://github.com/bokiex/eti_todo/issues/6. 

Test case needed to start working on the function.

**Comment by PolarcX** [comment]
Assigned @AlloyShears for this

**Comment by AlloyShears** [comment]
TC 06 - Filter function
Test Description: User filters for the results needed
Test Steps:
1. Go to To-Do page
2. Click on the filter button
3. Click on "Created by Owner" button in the drop down list

Expected results: Only the items created by Owner is retrieved from the database.
Test Values: NIL

TC 05-1 - To-Do Items created by team member not displayed
Test Description: User filters for To-Do items created by team member
Preconditions: Team member did not create any To-Do items
Test Steps:
1. Go to To-Do page
2. Click on the filter button
3. Click on "Created by Team member no. 1" button in the drop down list

Expected results:
Display "No results found" 
Empty page with no items retrieved from the database.

**Comment by AlloyShears** [comment]
@PolarcX pending review

**Comment by bokiex** [comment]
@AlloyShears Please re-do the test cases. The function is to show user specific to-dos rather than having a filter button.

**Comment by AlloyShears** [comment]
TC 06 - Filter function
Test Description: User can only view their own specific to-dos when logged in. User cannot view other user's to-do tasks.

Test Steps:
1. Go to To-Do page in the navigation bar.
2. View the to-do tasks.


Expected results: Only the items created by user is retrieved from the database. Other items from other users do not appear. 
Test Values: NIL

TC 06-1 - To-Do Items created by user(team member) is not displayed
Test Description: User has no to-do tasks.
Preconditions: Team member does not have any To-Do items.

Test Steps:
1. Open to-do page
2. View tasks to do

Expected results:
Display "No results found"
Empty page with no items retrieved from the database.

**Comment by bokiex** [comment]
Reviewed and closed
