### ISSUE TITLE
Test case for auto-archive and timestamp feature

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#19]
Auto-archive after addition and deletion of To-do items alongside timestamp upon creation of To-do item to be added for https://github.com/bokiex/eti_todo/issues/6 feature.

**Comment by PolarcX** [comment]
Assigned @AlloyShears for this

**Comment by AlloyShears** [comment]
TC07 - To-Do Page - Timestamp
Test description : The page should automatically display a timestamp for all To Do items created.
Preconditions: The user is logged in with a valid account.

Test Steps
1. Click the To-Do page button
2.  Create a To-Do item in the page
3. Key in "Sample item 1"
4. Click "Create" button to create the To-Do item

Expected result: In the To-Do page, the To-Do item should be displayed with the timestamp of the time it was created.

Test Values: To-Do Item name

**Comment by bokiex** [comment]
Reviewed and closed

**Comment by bokiex** [comment]
@AlloyShears Auto-archive feature test case still pending

**Comment by AlloyShears** [comment]
TC-08 - To-Do/Archive Page - Auto Archive feature
Test description : Auto-removed items are archived to the archive page from the to-do page.

Preconditions: The user is logged in with a valid account. User already has existing to-do items. 

Test Steps
1. Click the archive page button

Expected result: Archive page should be unfiltered and show every to-do task for the user that logged in.

Test Values: To-do items.

**Comment by bokiex** [comment]
Reviewed and closed
