### ISSUE TITLE
Test Cases for To-Do Page

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#2]

**Comment by PolarcX** [comment]
TC02 - To-Do Page - Page Shown
Test description : User that logged in can access the To-Do page in the website

Preconditions: The user is logged in with a valid account

Test Steps 
1. Log in into the website
2. Click on 'To-Do' in the Nav Bar

Expected result: Website should redirect the user to the 'To-Do' Page

Test Values: -Nil-

**Comment by Kaioru** [comment]
The to-do feature includes the creation, deletion and archiving of todo items and the current test cases do not test the functions fully. I'm reopening this issue for help with the test cases.

**Comment by PolarcX** [comment]
TC02 - To-Do Page - Page Shown
Test description : User that logged in can access the To-Do page in the website

Preconditions: The user is logged in with a valid account

Test Steps

Log in into the website
1. Click on 'To-Do' in the Nav Bar
2. Expected result: Website should redirect the user to the 'To-Do' Page

Test Values: -Nil-

TC02-1 - To-Do Page - Creation
Test description : User that logged in can access the To-Do page and create a new to do item

Preconditions: The user is logged in with a valid account

Test Steps

1. Log in into the website
2. Click on 'To-Do' in the Nav Bar
3. Click on 'Create new To-Do' button
4, Enter the title in 'title' field
5. Enter description in the 'description' field
7. Click 'Create'

Expected result: New To Do item is created is stored in the database

Test Values: 
Title = 'ETI CA2'
Description = 'CA2 For ETI'

TC02-2 - To-Do Page - Creation ( Same Title)
Test description : User creates a new to-do with the same title

Preconditions: The user is logged in with a valid account

Test Steps

1. Log in into the website
2. Click on 'To-Do' in the Nav Bar
3. Click on 'Create new To-Do' button
4, Enter the title in 'title' field
5. Enter description in the 'description' field
7. Click 'Create'

Expected result: 'Title has already exist' error should be shown, and item isn't stored in database

Test Values: 
Title = 'ETI CA2'
Description = 'CA2 For ETI'

TC02-3 - To-Do Page - Deletion
Test description : User that logged in can access the To-Do page and delete a to do item

Preconditions: The user is logged in with a valid account & records in database exists

Test Steps

1. Log in into the website
2. Click on 'To-Do' in the Nav Bar
3. Click on 'Delete To-Do' button
4, Choose which to delete
7. Click 'Delete'

Expected result: 'Successfully deleted' message should be shown & record is removed form the batabase

Test Values: -Nil-

TC02-4 - To-Do Page - Deletion ( no records )
Test description : User attempts to delete a to-do item when there are no records in the database

Preconditions: The user is logged in with a valid account & no records in database exists

Test Steps

1. Log in into the website
2. Click on 'To-Do' in the Nav Bar
3. Click on 'Delete To-Do' button


Expected result: 'Nothing to delete' message shows and nothing changes in the database

Test Values: -Nil-

TC02-5 - To-Do Page - Archive
Test description : User that logged in can access the To-Do page and archive a to do item

Preconditions: The user is logged in with a valid account & records in database exists

Test Steps

1. Log in into the website
2. Click on 'To-Do' in the Nav Bar
3. Click on 'Archive To-Do' button
4. Choose an item to be archived
5, Click on archive

Expected result: 'Successfully archived' message should show and status of the item in the database changes to archived

Test Values: -Nil-

**Comment by PolarcX** [comment]
@Kaioru @bokiex added more test cases, pending review

**Comment by bokiex** [comment]
Reviewed and closed
