### ISSUE TITLE
Sign up functionality 

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#20]
Test case for this function is here: https://github.com/bokiex/eti_todo/issues/17

Adds user credentials in the database and allows user to log in through Login Page

**Comment by Kaioru** [comment]
Assigning @bokiex for the implementation of this feature.
And @Swazztastic for the implementation of the test cases.

**Comment by bokiex** [comment]
Commit 3ff31121a003dcef35b72ffe1163cc22ddb6cbf7 adds the signup functionality. @Kaioru please review.

**Comment by Kaioru** [comment]
@bokiex Looks good, @Swazztastic can take over for the test cases for this.

**Comment by Swazztastic** [comment]
Test cases completed

**Comment by Swazztastic** [comment]
@bokiex Pending review

**Comment by bokiex** [comment]
Reviewed and closed
