### ISSUE TITLE
Filter functionality

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#23]
Test case for this functionality can be found here: https://github.com/bokiex/eti_todo/issues/18
 
Only to-do items specific to the user is to be shown to user.

**Comment by bokiex** [comment]
Assigning @Kaioru to this feature

**Comment by Kaioru** [comment]
196ccd8 implements this feature. @Swazztastic to work on the test cases for this.

**Comment by Swazztastic** [comment]
Test cases completed

**Comment by Swazztastic** [comment]
@bokiex Pending review

**Comment by bokiex** [comment]
Reviewed and closed
