### ISSUE TITLE
Test Cases for To-Do History Page

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#3]

**Comment by PolarcX** [comment]
Assigned @AlloyShears to handle test cases for To-Do History page

**Comment by AlloyShears** [comment]
TC02 - To-Do History Page - Page Shown
Test description : User can view the projects that are done.
Preconditions: The user is logged in with a valid account and has done at least 1 project.

Test Steps
1) Login to the website
2) Click on To-Do History button in the navigation bar

Expected result: Website should redirect the user to the 'To-Do History' Page. The page should display the projects done by the student. (SQLite)

Test Values: -Nil-

**Comment by AlloyShears** [comment]
@bokiex pending review :)

**Comment by PolarcX** [comment]
@AlloyShears Ok bro @bokiex Pending Review

**Comment by bokiex** [comment]
Reviewed and closed
