### ISSUE TITLE
Test Cases for Team Contributions Page

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#4]

**Comment by PolarcX** [comment]
Assigned @AlloyShears to handle test cases for team contributions page

**Comment by AlloyShears** [comment]
TC03 - Team contributions Page - Page Shown
Test description : User can view the commits done by different members of the team.
Preconditions: The user is logged in with a valid account and the each member of the team has done at least 1 commit.

Test Steps:
1)Login to the website
2)Click on Team contributions button in the navigation bar

Expected result: Website should redirect the user to the 'Team contributions' Page. The page should display the progress of the team's contributions.

Test Values: -Nil-

**Comment by AlloyShears** [comment]
@PolarcX pending review

**Comment by PolarcX** [comment]
@AlloyShears :ok_hand: 
@bokiex Pending Review

**Comment by bokiex** [comment]
Reviewed and closed

**Comment by bokiex** [comment]
Reopening issue as test case requires re-reviewing. 

TC03 - Team contributions Page - Page Shown
Test description : Display contributors and their roles in the project. 
Preconditions: User is signed in.

Test Steps:
1)Login to the website
2)Click on Team contributions button in the navigation bar

Expected result: Team contribution page shows up with members of the team and their roles listed

Test Values: -Nil-

@AlloyShears please review.

**Comment by Kaioru** [comment]
According to the requirements document, team contributions is actually out of scope when it comes to testing.

**Comment by bokiex** [comment]
Okay, thanks for the clarification. Issue is closed
