### ISSUE TITLE
Authentication Feature 

### ISSUE THREAD

**Issue by bokiex** [bokiex/eti_todo#5]
Authentication Test Case: https://github.com/bokiex/eti_todo/issues/1
Feature must encompass everything under the test case.

**Comment by Kaioru** [comment]
I've assigned @Swazztastic for help with the test cases. @bokiex will be developing the feature.

**Comment by bokiex** [comment]
82d452eb39fa089a4a3ddba249f07d5a8bac02e8

**Comment by Kaioru** [comment]
The 82d452e commit breaks when running migrations, this might be due to migrations not being created in the repo. I've attached the error log for review.


<img width="765" alt="image" src="https://user-images.githubusercontent.com/6829787/70368411-e3b32500-18e4-11ea-983a-b0d3243b9690.png">

**Comment by bokiex** [comment]
f393fc6e0a026520043bb0fde0b8e02b72367dcb commit added migrations, @Kaioru please review.

**Comment by Kaioru** [comment]
Looks good.
